error: Don't export Error::strerror method
The method is intended to do just a conversion of the error to a
description of it, so we have `Display` trait for this purpose and this
method does not need to be accessed directly.

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>